CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,,
    CONSTRAINT fk_role
      FOREIGN KEY (role_id) REFERENCES roles(id),
);
